FROM readytalk/nodejs

WORKDIR /webapp

ADD package.json /webapp/

RUN npm install

ADD . /webapp

env STORMPATH_CLIENT_APIKEY_ID=20NSYHA935V0GK6D9NLQ3G6CW
env STORMPATH_CLIENT_APIKEY_SECRET=fVRGQ79DVoSRpYFHc18ZVHZBt87BAR+NFza49JVU0mM
env STORMPATH_APPLICATION_HREF=https://api.stormpath.com/v1/applications/1IGbKvjJ9dDDGLsAGblQYI

EXPOSE 8500

ENTRYPOINT ["node", "app.js"]